name: Deploy Telegram Bot

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to Cityhost
        env:
          DO_HOST: ${{ secrets.DO_HOST }}
          DO_USER: ${{ secrets.DO_USER }}
        run: |
          ssh -o StrictHostKeyChecking=no $DO_USER@$DO_HOST << 'EOF'
            cd /opt/telegram_bot
            git pull origin main
            pipenv install --deploy --ignore-pipfile
            systemctl restart telegram_bot.service
          EOF
